const PRISM_LANGUAGES: Record<string, string> = {
  js: 'javascript',
  jsx: 'jsx',
  ts: 'typescript',
  tsx: 'tsx',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  html: 'markup',
  htm: 'markup',
  json: 'json',
  json5: 'json5',
  md: 'markdown',
  mdx: 'markdown',
  py: 'python',
  pyw: 'python',
  rb: 'ruby',
  go: 'go',
  mod: 'go-module',
  rs: 'rust',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  swift: 'swift',
  php: 'php',
  sql: 'sql',
  yaml: 'yaml',
  yml: 'yaml',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  xml: 'markup',
  vue: 'markup',
  svg: 'markup',
  c: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  cs: 'csharp',
  h: 'c',
  hpp: 'cpp',
  zig: 'zig',
  lua: 'lua',
  dart: 'dart',
  hs: 'haskell',
  lhs: 'haskell',
  scala: 'scala',
  sc: 'scala',
  nim: 'nim',
  nimble: 'nim',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hrl: 'erlang',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  edn: 'clojure',
  groovy: 'groovy',
  gy: 'groovy',
  gvy: 'groovy',
  pl: 'perl',
  pm: 'perl',
  ps1: 'powershell',
  psm1: 'powershell',
  pssc: 'powershell',
  fs: 'fsharp',
  fsi: 'fsharp',
  fsx: 'fsharp',
  ml: 'ocaml',
  mli: 'ocaml',
  sol: 'solidity',
  toml: 'toml',
  makefile: 'makefile',
  mk: 'makefile',
  cmake: 'cmake',
  gradle: 'gradle',
  ini: 'ini',
  cfg: 'ini',
  graphql: 'graphql',
  gql: 'graphql',
  pug: 'pug',
  jade: 'pug',
  less: 'less',
  styl: 'stylus',
  coffee: 'coffeescript',
  jl: 'julia',
  r: 'r',
  R: 'r',
  vb: 'vbnet',
  proto: 'protobuf',
  nginx: 'nginx',
  diff: 'diff',
  patch: 'diff',
  csv: 'csv',
  rst: 'rest',
  tex: 'latex',
  latex: 'latex',
  m: 'objectivec',
  mm: 'objectivec',
  gd: 'gdscript',
  glsl: 'glsl',
  vert: 'glsl',
  frag: 'glsl',
  v: 'verilog',
  sv: 'verilog',
  vhd: 'vhdl',
  vhdl: 'vhdl',
  wat: 'wasm',
  ll: 'llvm',
  d: 'd',
  cr: 'crystal',
  f: 'fortran',
  f90: 'fortran',
  f95: 'fortran',
  nix: 'nix',
  hcl: 'hcl',
  tf: 'hcl',
  tfvars: 'hcl',
  properties: 'properties',
  props: 'properties',
  editorconfig: 'editorconfig',
  dot: 'dot',
  mermaid: 'mermaid',
  mmd: 'mermaid',
};

export const LANGUAGE_LABEL: Record<string, string> = {
  plain: 'Plain text',
  markdown: 'Markdown',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  json: 'JSON',
  html: 'HTML',
  css: 'CSS',
  python: 'Python',
  bash: 'Bash',
};

export function getPrismLanguage(filename: string): string {
  const baseName = filename.includes('/') ? filename.slice(filename.lastIndexOf('/') + 1) : filename;
  if (baseName === 'Dockerfile' || baseName.startsWith('Dockerfile.')) {
    return 'docker';
  }
  if (baseName === 'Makefile' || baseName === 'makefile') {
    return 'makefile';
  }
  const ext = baseName.includes('.') ? baseName.slice(baseName.lastIndexOf('.') + 1).toLowerCase() : '';
  return PRISM_LANGUAGES[ext] ?? 'plain';
}
